### PR TITLE
sort symbols when printing

### PR DESCRIPTION
**Pull request by zapashcanon**
to get a more stable output

### CODE REVIEW

**Comment by filipeom** [comment]
Thanks! :smile:

**Comment by zapashcanon** [comment]
Wait, don't merge this for now. Something is weird with the output. :sweat_smile:

**Comment by filipeom** [comment]
Yeah, I'm not actually sure I like how floats are being displayed also :disappointed:

**Comment by zapashcanon** [comment]
OK so the problem was that I used polymorphic compare and the type of of symbols being `{ sort : Ty.t; name : String.t }`, the `sort` field was compared first...

I defined proper compare functions to avoid this. (In a few places I still used a polymorphic compare but I believe they don't really matter).

**Comment by filipeom** [comment]
Okok, makes sense! Merging, thanks!

**Pull request merged**
